CompileFlags:
  Add: [-Wno-pre-c++17-compat,-Wno-pre-c++14-compat]
Diagnostics: 
  UnusedIncludes: "Strict"
  ClangTidy:
    Add: ["readability-braces-around-statements", "readability-else-after-return"]
    CheckOptions:
      readability-identifier-naming.ClassMethodCase: lower_case
      llvm-namespace-comment.ShortNamespaceLines: '10'
      llvm-namespace-comment.SpacesBeforeComments: '2'
      misc-unused-parameters.StrictMode: '1'
      readability-braces-around-statements.ShortStatementLines: '2'
      readability-identifier-naming.ClassCase: CamelCase
      readability-identifier-naming.EnumCase: CamelCase
      readability-identifier-naming.UnionCase: CamelCase
      readability-identifier-naming.FunctionCase: lower_case
      readability-identifier-naming.VariableCase: lower_case
      readability-identifier-naming.ProtectedMemberSuffix: '_'
      readability-identifier-naming.PrivateMemberSuffix: '_'
      readability-identifier-naming.EnumConstantCase: UPPER_CASE
      readability-identifier-naming.StaticVariableCasePrefix: 's_'
      readability-identifier-naming.StaticConstantCase: UPPER_CASE
      readability-identifier-naming.GlobalConstantCase: UPPER_CASE
      readability-identifier-naming.ClassConstantCase: UPPER_CASE
